[package]
name = "jisp_sha3_gui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jisp_sha3 = {path = "../jisp_sha3" }
eframe = "0.27.2"